import { Course, UserProfile } from '@/types';

export const ACADEMY_INFO = {
  name: 'SkillUp Academy',
  tagline: 'Learn New Skills. Build Your Future.',
  description: 'Practical, industry-focused training courses taught by experienced mentors. Flexible schedules for working professionals and aspiring learners.',
  contactEmail: 'admissions@skillupacademy.edu',
  phone: '+1 (555) 234-5678',
  address: '742 Evergreen Terrace, Tech District, CA',
};

export const COURSE_CATEGORIES = [
  'All',
  'Programming',
  'Data Science',
  'Design',
  'Business',
  'Digital Marketing',
  'Language',
] as const;

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-web-dev-bootcamp',
    title: 'Full-Stack Web Development Bootcamp',
    short_description: 'Master modern frontend & backend web development from HTML/CSS to React, Next.js, and Supabase.',
    description: 'This comprehensive bootcamp takes you from absolute beginner to confident full-stack web developer. You will build dynamic, responsive web applications with modern technologies including React 19, Next.js App Router, Tailwind CSS, REST APIs, and Supabase PostgreSQL. By the end of this course, you will have a portfolio of 4 production-ready web apps.',
    category: 'Programming',
    instructor: 'Alex Rivera',
    image_url: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=1200&auto=format&fit=crop',
    duration: '8 Weeks',
    schedule: 'Saturday & Sunday',
    class_time: '10:00 AM – 12:30 PM',
    level: 'Beginner',
    price: 120,
    available_seats: 12,
    capacity: 25,
    status: 'open',
    rating: 4.9,
    what_you_will_learn: [
      'HTML5, Modern CSS3 & Tailwind CSS styling',
      'JavaScript ES6+ fundamentals, DOM manipulation & async programming',
      'React component architecture, custom hooks & state management',
      'Full-stack Next.js with Server Components & API routes',
      'Database modeling, Supabase authentication & PostgreSQL queries',
      'Deploying production applications to Vercel and custom domains',
    ],
  },
  {
    id: 'course-python-data-science',
    title: 'Python for Data Science & Machine Learning',
    short_description: 'Analyze real-world datasets, build predictive models, and master Pandas, NumPy, and Scikit-Learn.',
    description: 'Unlock the power of data with Python. In this hands-on course, you will learn data cleaning, exploratory data analysis, data visualization, and applied machine learning. Work with real-world datasets in Jupyter notebooks and build models for classification, regression, and customer clustering.',
    category: 'Data Science',
    instructor: 'Dr. Sarah Chen',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    duration: '6 Weeks',
    schedule: 'Tuesday & Thursday',
    class_time: '6:30 PM – 8:30 PM',
    level: 'Intermediate',
    price: 150,
    available_seats: 8,
    capacity: 20,
    status: 'open',
    rating: 4.8,
    what_you_will_learn: [
      'Python programming for scientific computing & data structures',
      'Data manipulation & wrangling with Pandas and NumPy',
      'Interactive dashboards & charts with Matplotlib & Seaborn',
      'Statistical hypothesis testing and feature engineering',
      'Supervised & unsupervised machine learning with Scikit-Learn',
      'Deploying data science models with Streamlit',
    ],
  },
  {
    id: 'course-ui-ux-design',
    title: 'UI/UX Design Masterclass with Figma',
    short_description: 'Learn wireframing, modern UI design systems, interactive prototyping, and user testing in Figma.',
    description: 'Turn ideas into intuitive, beautiful digital products. This practical course covers the complete product design cycle: user research, wireframing, design tokens, responsive typography, interactive component states, micro-interactions, and developer handoff in Figma.',
    category: 'Design',
    instructor: 'Elena Rostova',
    image_url: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?q=80&w=1200&auto=format&fit=crop',
    duration: '5 Weeks',
    schedule: 'Monday & Wednesday',
    class_time: '7:00 PM – 9:00 PM',
    level: 'Beginner',
    price: 95,
    available_seats: 15,
    capacity: 25,
    status: 'open',
    rating: 4.9,
    what_you_will_learn: [
      'User research methodologies, personas & user journeys',
      'Figma auto-layout, component variants & design tokens',
      'Building cohesive design systems and color palettes',
      'Interactive high-fidelity prototyping and animations',
      'Usability testing heuristics & accessibility standards (WCAG)',
      'Design handoff and collaboration with developers',
    ],
  },
  {
    id: 'course-digital-marketing',
    title: 'Digital Marketing & Growth Hacking',
    short_description: 'Master SEO, Google Ads, social media strategy, content marketing, and conversion optimization.',
    description: 'Grow businesses and drive qualified traffic. Learn the exact growth strategies used by top tech startups to acquire customers cost-effectively. Covers Google Ads, search engine optimization (SEO), Meta advertising, email marketing funnels, and web analytics.',
    category: 'Digital Marketing',
    instructor: 'Marcus Vance',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    duration: '4 Weeks',
    schedule: 'Friday & Saturday',
    class_time: '2:00 PM – 4:30 PM',
    level: 'Beginner',
    price: 80,
    available_seats: 18,
    capacity: 30,
    status: 'open',
    rating: 4.7,
    what_you_will_learn: [
      'Technical SEO audits, keyword research & backlink strategies',
      'Paid search campaigns with Google Ads and keyword bidding',
      'High-converting social ad campaigns on Meta & TikTok',
      'Email marketing automation and nurture workflows',
      'Conversion rate optimization (CRO) & A/B testing',
      'Google Analytics 4 and attribution reporting',
    ],
  },
  {
    id: 'course-business-strategy',
    title: 'Business Strategy & Product Management',
    short_description: 'Learn product roadmap planning, unit economics, market validation, and agile leadership.',
    description: 'Bridge the gap between technology and business goals. Designed for aspiring product managers and entrepreneurs, this course covers customer discovery, product-market fit validation, roadmap prioritization frameworks (RICE/MoSCoW), financial modeling, and leading cross-functional teams.',
    category: 'Business',
    instructor: 'David Sterling',
    image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop',
    duration: '6 Weeks',
    schedule: 'Tuesday & Thursday',
    class_time: '7:00 PM – 9:00 PM',
    level: 'Intermediate',
    price: 135,
    available_seats: 6,
    capacity: 20,
    status: 'open',
    rating: 4.8,
    what_you_will_learn: [
      'Product discovery, customer interviews & problem validation',
      'Unit economics, CAC, LTV & SaaS business metrics',
      'Strategic roadmap prioritization & OKR frameworks',
      'Agile product execution, sprint planning & user stories',
      'Go-to-market (GTM) launch strategy and competitive analysis',
      'Pitch deck preparation and stakeholder communication',
    ],
  },
  {
    id: 'course-business-english',
    title: 'Professional Business Communication',
    short_description: 'Sharpen your executive writing, presentation delivery, and international negotiation skills.',
    description: 'Communicate with clarity, confidence, and authority in international business environments. Learn to craft persuasive emails and reports, lead high-stakes client meetings, and deliver compelling presentations without hesitation.',
    category: 'Language',
    instructor: 'Claire Dupont',
    image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1200&auto=format&fit=crop',
    duration: '4 Weeks',
    schedule: 'Saturday & Sunday',
    class_time: '3:00 PM – 5:00 PM',
    level: 'Beginner',
    price: 60,
    available_seats: 0,
    capacity: 15,
    status: 'closed',
    rating: 4.9,
    what_you_will_learn: [
      'Executive email drafting and formal report structure',
      'Leading confident video conferences and global team meetings',
      'Public speaking, slide deck delivery & voice modulation',
      'Negotiation terminology and persuasive phrasing',
      'Cross-cultural business etiquette and diplomacy',
    ],
  },
];

export const DEMO_USER: UserProfile = {
  id: '5a4075a8-8cb8-4215-9032-32258c57567e',
  full_name: 'Alex Johnson',
  email: 'alex.learner@example.com',
};

// Backward compatibility
export const DEMO_STUDENT = DEMO_USER;
